#!/usr/bin/env bash

echo '     _       _    __ _ _           '
echo '  __| | ___ | |_ / _(_) | ___  ___ '
echo ' / _` |/ _ \| __| |_| | |/ _ \/ __|'
echo '| (_| | (_) | |_|  _| | |  __/\__ \'
echo ' \__,_|\___/ \__|_| |_|_|\___||___/'
echo

# Dotfiles directory
DOTFILES="$HOME/.dotfiles"

# TODO

exit 0
